new site
umputun/remark42 pull request #1036
Opened 2021-06-06 20:42 UTC by akellbl4

I've redeveloped the site with Eleventy. It's an alternative for Hugo with a much friendly API and DX.
Finally, we've got working navigation in docs.

- [ ] add links on next/prev pages at the end of doc pages
Maybe features down below better do in separate PR and release new site sooner.
- [ ] add table of content
- [ ] implement dark theme
- [ ] implement theme switcher
- [ ] implement page with a list of the releases

2021-06-06 20:43 UTC, akellbl4 commented
@paskal I've created a structure of content. If you have any ideas we can change it.

2021-06-07 21:10 UTC, paskal requested changes

2021-06-07 21:10 UTC, paskal commented on site/.dockerignore
> +node_modules
/site should have its own Readme.md

2021-06-07 21:10 UTC, paskal commented on site/Dockerfile
> +COPY ../docs /site/src/docs
I can't build it, unfortunately:

```
 > [4/5] COPY ../docs /site/src/docs:
------
failed to compute cache key: "/docs" not found: not found
```
Also, I don't know what would be the result given the fact that the run CMD sleeps.

2021-06-11 18:21 UTC, akellbl4 commented
@paskal thank you for help!

2021-06-12 21:55 UTC, paskal commented
Really nice site! Few things I found so far:

- Main page has extra empty `<li>` element
  <img width="681" alt="image" src="https://user-images.githubusercontent.com/712534/121789745-d01f0380-cbd8-11eb-9052-728330617ec3.png">
- /docs/system-requirments/ should be /docs/system-requirements/, also edit button leads to `https://github.com/umputun/remark42/edit//src/docs/getting-started/system-requirments/index.md` with two slashes, one is redundant
- in my case, `docker-compose run build` generates the site properly, but `docker-compose up server` serves the site without style.css
- Right now the site generated with `docker-compose run build` is empty, current documentation is not included: what I see is plenty of empty pages, /docs/contributing/technical-details/ is the only one I found with text.

2021-06-13 08:00 UTC, akellbl4 commented
But> but docker-compose up server serves the site without style.css

Strange, works good for me.

> Right now, the site generated with docker-compose run build is empty, current documentation is not included: what I see is plenty of empty pages, /docs/contributing/technical-details/ is the only one I found with text.

I've created proper structure for docs but haven't moved them to the site yet.
If anybody can help with it would be great.

> code on the only page with text I have is wrapped in apostrofs

They are backticks and it's intentional. I use default styles for it from tailwind.

> The 404 page you designed is not shown on the yarn dev run. For consistency, I would propose fixing that as well.

As far as I know dev server doesn't support custom 404 and it can be reached by open `/404/`. In production configuration should refer to that page for displaying 404

2021-06-13 08:06 UTC, akellbl4 commented
> - Main page has extra empty `<li>` element
>  <img width="681" alt="image" src="https://user-images.githubusercontent.com/712534/121789745-d01f0380-cbd8-11eb-9052-728330617ec3.png">

I've fixed this bug. It was bad support for the dark theme on the main page.

2021-06-13 09:04 UTC, akellbl4 commented
Live demo:
https://remark42.vercel.app/

2021-06-13 10:33 UTC, akellbl4 commented
> /docs/system-requirments/ should be /docs/system-requirements/, also edit button leads to https://github.com/umputun/remark42/edit//src/docs/getting-started/system-requirments/index.md with two slashes, one is redundant

2021-06-13 12:12 UTC, akellbl4 commented
@paskal try to run the server in docker. looks like I've fixed it.

2021-06-13 12:17 UTC, akellbl4 commented
@paskal @umputun 
I've done everything from the code perspective. Feel free to test and comment.
I think this PR is good to merge. I created a basic structure for docs to demonstrate how navigation works. We can do all of the work on migration docs in a separate PR.

2021-06-13 17:30 UTC, paskal approved these changes

2021-06-13 22:40 UTC, merged