add docs from readme on the site
umputun/remark42 pull request #1062
Opened 2021-07-26 08:46 UTC by akellbl4

2021-07-26 09:01 UTC, paskal requested changes
Few small things. I see that some text was not copied as-is from the current master but was altered, I propose you to re-check only altered parts and update them from upstream when possible.

2021-07-26 09:03 UTC, akellbl4 commented on site/src/docs/configuration/authorization/index.md
> +## Telegram Auth Provider
I changes order regarding to auth methods. OAuth first and others methods then

2021-07-26 09:11 UTC, akellbl4 commented on site/src/docs/backup/migration/index.md
> +### Importfrom Disqus
What space is missing?

2021-07-27 08:14 UTC, paskal approved these changes

2021-07-27 09:22 UTC, merged