Use custom userID
umputun/remark42 pull request #1235
Opened 2022-01-19 10:34 UTC by paleale

2022-01-19 19:33 UTC, umputun requested changes
Thx for the pr!

I think it makes sense to extend user id returned by AddDirectProviderWithUserIDFunc with X-Forwarded-For and X-Real-IP. Pls note - we likely should also handle chains of reported ips from those headers as each proxy level may append its ip. 

Probably smth similar to [this](https://github.com/go-chi/chi/blob/master/middleware/realip.go)

2022-01-20 07:57 UTC, paskal commented on backend/app/cmd/server.go
> +			func(user string, r *http.Request) string {
I propose to add a comment here, something like "Custom user ID generator, used to distinguish anonymous users coming from different IPs".

2022-02-18 22:00 UTC, umputun commented
@paleale pls let me know if you are planning to make the proposed change

2022-03-10 09:39 UTC, paleale commented
@umputun I am, back again, still uncertain about all the possible force majors, but I'd like to finish that at nearest holidays.

2022-05-10 16:57 UTC, umputun commented
My comment was probably inaccurate, or i have added it before we had `RealIP` middleware added. With this middleware in place your `user + r.RemoteAddr` should be fine. Pls, make sure the conflict resolved and I'll merge

2022-05-10 17:57 UTC, paskal approved these changes

2022-05-10 17:58 UTC, umputun approved these changes
LGTM, thx

2022-05-10 17:59 UTC, merged