use workspaces
umputun/remark42 pull request #1417
Opened 2022-07-13 03:53 UTC by akellbl4

2022-07-13 18:14 UTC, akellbl4 commented on frontend/.lintstagedrc.js
>  module.exports = {
Should we use shared lint-staged config or should we have config per package?

If it is shared probably all of the lint/format packages should be shared as well

2022-07-19 21:39 UTC, Mavrin approved these changes

2022-07-19 21:39 UTC, Mavrin commented on Dockerfile
> +CMD ["/srv/remark42", "server"]
Add new line please

2022-07-19 21:39 UTC, Mavrin commented on Dockerfile.artifacts
> +CMD ["sleep", "100"]
Add new line please

2022-07-19 22:39 UTC, paskal requested changes
LGTM, except for the fact that this change can't go without a single `.md` file change. Something should be altered in the frontend dev documentation and maybe a Readme file.

2022-07-20 00:15 UTC, paskal commented
Also please don't merge before #1422, I would like to rebase with newer Dockerfile.

2022-07-20 02:04 UTC, paskal commented
To be precise, I want to see edits in https://github.com/umputun/remark42/blob/master/site/src/docs/contributing/development/frontend/index.md.

2022-07-20 18:22 UTC, paskal submitted a review, later dismissed

2022-07-21 23:07 UTC, paskal approved these changes

2022-07-21 23:27 UTC, merged