Cleanup of the frontend code
umputun/remark42 pull request #1563
Opened 2023-01-08 12:27 UTC by paskal

My shot at #1321.

- fix typos
- add missing dev `process` dependency
- replace undocumented `substr` with `substring`
- remove unused code
- inline a few variables
- simplify ifs when possible
- improve saveCollapsedComments documentation
- cleanup the unused imports
- remove unused variables and types

2023-01-08 17:00 UTC, akellbl4 commented on frontend/apps/remark42/app/components/comment-form/comment-form.tsx
> +        errorMessage: extractErrorMessageFromResponse(e as FetcherError, this.props.intl),
to be honest assertion isn't better but we can let it be

2023-01-08 17:01 UTC, akellbl4 commented on frontend/apps/remark42/app/components/comment/comment-votes.tsx
> +      setErrorMessage(extractErrorMessageFromResponse(err as FetcherError, intl));
Same here, we should check type of error before passing in into extract function like `err instanceof FectherError`

2023-01-08 17:02 UTC, akellbl4 commented on frontend/apps/remark42/app/components/comment/comment.tsx
> -
👍

2023-01-08 17:02 UTC, akellbl4 commented on frontend/apps/remark42/app/components/settings/settings.tsx
> +    return this.state.unhiddenUsers.indexOf(user.id) === -1;
let's use `includes` which returns `boolean`

2023-01-08 17:03 UTC, akellbl4 commented on frontend/apps/remark42/app/typings/global.d.ts
> +  namespace NodeJS {}
we can remove it completely

2023-01-08 17:04 UTC, akellbl4 commented on frontend/apps/remark42/app/utils/loadLocale.ts
> +      .catch(() => enMessages);
this file is autogenerated we shouldn't do any formatting here

2023-01-08 17:05 UTC, akellbl4 commented on frontend/apps/remark42/package.json
> +    "process": "^0.11.10",
`process` is global variable, we don't need this package

2023-01-08 17:07 UTC, akellbl4 requested changes
@paskal I like those changes. I wrote few points which we should fix before merging it.

2023-01-08 17:15 UTC, akellbl4 commented
I just realized that you tried to address https://github.com/umputun/remark42/issues/1321. I'd say it's less than ideal way of addressing it, so I'd rather leave `ts-ignore` because assertions is nothing better that ignores because types are still unsafe.

2023-01-09 21:00 UTC, akellbl4 approved these changes
@paskal nice job!

2023-01-09 21:01 UTC, umputun approved these changes

2023-01-09 21:16 UTC, merged